(function(){
var h=this,aa=null;var ba=function(){},m=function(a){return"function"==typeof a},v=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ca=function(a,b){if(Array.prototype.indexOf){var d=a.indexOf(b);return"number"==typeof d?d:-1}for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1},da=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},ea=function(a){return Math.round(Number(a))||0},w=function(){this.prefix="gtm.";this.w={}};w.prototype.set=function(a,b){this.w[this.prefix+a]=b};
w.prototype.get=function(a){return this.w[this.prefix+a]};w.prototype.contains=function(a){return void 0!==this.get(a)};
var fa=function(a,b,d){try{return a["10"](a,b||ba,d||ba)}catch(c){}return!1},ga=function(a,b){function d(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var c=da(b).split("&"),e=0;e<c.length;e++)if(c[e]){var f=c[e].indexOf("=");0>f?d(c[e],"1"):d(c[e].substring(0,f),c[e].substring(f+1))}},ha=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},ia=function(a){this.list=[];if(v(a))for(var b=0;b<a.length;b++)this.list.push(String(a[b]))},ja=function(a,b){var d=b["10"],
c;if(!(c=0<=ca(a.list,d.b)))e:{for(var e=a.list,f=d.c||[],g=new w,k=0;k<e.length;k++)g.set(e[k],!0);for(k=0;k<f.length;k++)if(g.get(f[k])){c=!0;break e}c=!1}return c},ka=function(a){for(var b=0;b<a.length;b++)a[b]()},la=function(){var a=this;this.g=!1;this.m=[];this.k=[];this.B=function(){a.g||ka(a.m);a.g=!0};this.A=function(){a.g||ka(a.k);a.g=!0}},ma=function(){this.n=[];this.f=0};ma.prototype.addListener=function(a){this.n.push(a)};
var na=function(a,b){if(!b.g){a.f++;var d=function(){0<a.f&&a.f--;0<a.f||ka(a.n)};b.m.push(d);b.k.push(d)}};var x=window,y=document,z=function(a,b){var d=x[a],c="var "+a+";";if(h.execScript)h.execScript(c,"JavaScript");else if(h.eval)if(null==aa&&(h.eval("var _et_ = 1;"),"undefined"!=typeof h._et_?(delete h._et_,aa=!0):aa=!1),aa)h.eval(c);else{var e=h.document,f=e.createElement("script");f.type="text/javascript";f.defer=!1;f.appendChild(e.createTextNode(c));e.body.appendChild(f);e.body.removeChild(f)}else throw Error("goog.globalEval not available");x[a]=void 0===d?b:d;return x[a]},B=function(a,b,d){return("http:"==
x.location.protocol?b:a)+d},oa=function(a){var b=y.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},pa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},C=function(a,b,d){var c=y.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;pa(c,b);d&&(c.onerror=d);oa(c)},qa=function(a,b){var d=y.createElement("iframe");d.height="0";d.width="0";d.style.display="none";d.style.visibility=
"hidden";oa(d);pa(d,b);void 0!==a&&(d.src=a);return d},F=function(a,b,d){var c=new Image(1,1);c.onload=function(){c.onload=null;b&&b()};c.onerror=function(){c.onerror=null;d&&d()};c.src=a},G=function(a,b,d,c){a.addEventListener?a.addEventListener(b,d,!!c):a.attachEvent&&a.attachEvent("on"+b,d)},ra=!1,sa=[],I=function(a){if(!(a&&"readystatechange"==a.type&&"interactive"!=y.readyState&&"complete"!=y.readyState||ra)){ra=!0;for(var b=0;b<sa.length;b++)sa[b]()}},ta=0,ua=function(){if(!ra&&140>ta){ta++;
try{y.documentElement.doScroll("left"),I()}catch(a){x.setTimeout(ua,50)}}},va=!1,ya=[],za=function(){if(!va){va=!0;for(var a=0;a<ya.length;a++)ya[a]()}};var J=new w,Aa=ba,M=[],Ba=!1,Ca=function(a){var b=!1;return function(){!b&&m(a)&&x.setTimeout(a,0);b=!0}},Da=function(){for(var a=!1;!Ba&&0<M.length;){Ba=!0;var b=M.shift(),d=void 0;for(d in b)b.hasOwnProperty(d)&&J.set(d,b[d]);var c=b.event,a=(c?Aa(c,Ca(b.eventCallback)):!1)||a;Ba=!1}return!a};var Ea=null;var _e=function(){return Ea};_e.b="e";var _v=function(a){var b=J.get(a["14"]);return void 0!==b?b:a[""]};_v.b="v";var _f=function(){return String(J.get("gtm.referrer")||y.referrer)};_f.b="f";
var Fa=y.createElement("a"),Ga=function(a){var b=x.location,d=b.hash?b.href.replace(b.hash,""):b.href,c=J.get("gtm.url");c&&(Fa.href=d=String(c),b=Fa);var e=(b.protocol.replace(":","")||x.location.protocol.replace(":","")).toLowerCase();switch(a["6"]){case "protocol":d=e;break;case "host":d=(b.hostname||x.location.hostname).split(":")[0].toLowerCase();break;case "port":d=String(1*(b.hostname?b.port:x.location.port)||("http"==e?80:"https"==e?443:""));break;case "path":d="/"==b.pathname.substr(0,1)?b.pathname:"/"+b.pathname;
break;case "query":d=b.search.replace("?","");break;case "fragment":d=b.hash.replace("#","")}
return d},_u=Ga;_u.b="u";var _eq=function(a){return String(a["2"])==String(a["3"])};_eq.b="eq";var _re=function(a){return RegExp(a["3"],a[""]?"i":void 0).test(a["2"])};_re.b="re";var O,La,Ma,Na,Oa=function(){return h.navigator?h.navigator.userAgent:null};Na=Ma=La=O=!1;var Pa;if(Pa=Oa()){var Qa=h.navigator;O=0==Pa.indexOf("Opera");La=!O&&-1!=Pa.indexOf("MSIE");Ma=!O&&-1!=Pa.indexOf("WebKit");Na=!O&&!Ma&&"Gecko"==Qa.product}var P=La,Ra=Na,Sa=Ma,Ta=function(){var a=h.document;return a?a.documentMode:void 0},Ua;
e:{var Va="",Q;if(O&&h.opera)var Wa=h.opera.version,Va="function"==typeof Wa?Wa():Wa;else if(Ra?Q=/rv\:([^\);]+)(\)|;)/:P?Q=/MSIE\s+([^\);]+)(\)|;)/:Sa&&(Q=/WebKit\/(\S+)/),Q)var Xa=Q.exec(Oa()),Va=Xa?Xa[1]:"";if(P){var Ya=Ta();if(Ya>parseFloat(Va)){Ua=String(Ya);break e}}Ua=Va}
var Za=Ua,$a={},R=function(a){var b;if(!(b=$a[a])){for(var d=0,c=String(Za).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(c.length,e.length),g=0;0==d&&g<f;g++){var k=c[g]||"",l=e[g]||"",n=RegExp("(\\d*)(\\D*)","g"),q=RegExp("(\\d*)(\\D*)","g");do{var p=n.exec(k)||["","",""],r=q.exec(l)||["","",""];if(0==p[0].length&&0==r[0].length)break;d=((0==p[1].length?0:parseInt(p[1],10))<(0==r[1].length?0:parseInt(r[1],10))?-1:(0==p[1].length?
0:parseInt(p[1],10))>(0==r[1].length?0:parseInt(r[1],10))?1:0)||((0==p[2].length)<(0==r[2].length)?-1:(0==p[2].length)>(0==r[2].length)?1:0)||(p[2]<r[2]?-1:p[2]>r[2]?1:0)}while(0==d)}b=$a[a]=0<=d}return b},ab=h.document,bb=ab&&P?Ta()||("CSS1Compat"==ab.compatMode?parseInt(Za,10):5):void 0;if(Ra||P){var eb;if(eb=P)eb=P&&9<=bb;eb||Ra&&R("1.9.1")}P&&R("9");var jb=function(a,b){var d="";P&&!fb(a)&&(d='<script>document.domain="'+document.domain+'";\x3c/script>'+d);var c="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+d+"</head><body>"+b+"</body></html>";if(gb)a.srcdoc=c;else if(hb){var e=a.contentWindow.document;e.open("text/html","replace");e.write(c);e.close()}else ib(a,c)},gb=Sa&&"srcdoc"in document.createElement("iframe"),hb=Ra||Sa,ib=function(a,b){P&&(R(7)&&!R(10))&&kb(b)&&(b=lb(b));var d=function(){a.contentWindow.goog_content=
b;a.src="javascript:window.goog_content"};P&&!fb(a)?mb(a,d):d()},fb=function(a){try{return Boolean(a.contentWindow.document)}catch(b){return!1}},nb=0,mb=function(a,b){var d="goog_rendering_callback"+nb++;window[d]=b;P&&R(6)&&!R(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+d+";window.parent."+d+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":
a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+d+";window.parent."+d+" = null;continuation();})()\x3c/script>'"},kb=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},lb=function(a){for(var b=unescape(encodeURIComponent(a)),d=Math.floor(b.length/2),c=[],e=0;e<d;++e)c[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(c[d]=b.charAt(b.length-1));return c.join("")};var tb,S;
var Bb=function(a){return function(){}},Cb=function(a){return function(){}};
var _ga=function(a,b,d){function c(a){var b=[].slice.call(arguments,0);b[0]=p+b[0];q.push(b)}function e(b,d){void 0!==a[d]&&c(b,a[d])}function f(b,d){void 0!==a[d]&&c(b,Number(a[d]))}function g(a,b){if(b)for(var d=0;d<b.length;d++){var e=[a];v(b[d])?e.push.apply(e,b[d]):e.push(b[d]);"_setCustomVar"==e[0]&&void 0===e[3]||c.apply(this,e)}}function k(b,d){void 0!==a[d]&&c("_set",b,a[d])}function l(b,c){void 0!==a[c]&&(r+="&"+b+"="+a[c])}function n(a,b){r+="&"+a+"="+b}var q=z("_gaq",[]),p="";void 0==
a["18"]?p=(new Date).getTime()+".":""!==a["18"]&&(p=a["18"]+".");e("_setAccount","0");
k("page","15");e("_setDomainName","9");
e("_setAllowLinker","1");var r="";
if(""!==r){var t=new w,A="?"==x.location.search.charAt(0)?x.location.search.substring(1):x.location.search,K="#"==x.location.hash.charAt(0)?x.location.hash.substring(1):x.location.hash;A&&ga(t,A);K&&a[""]&&ga(t,K);t.contains("gclid")&&n("gclid",ha(t.get("gclid")));t.contains("gclsrc")&&n("gclsrc",ha(t.get("gclsrc")));t.contains("dclid")&&n("dclid",ha(t.get("dclid")));c("_set","campaignParams",r)}a["12"]&&c("_require","inpage_linkid","//www.google-analytics.com/plugins/ga/inpage_linkid.js");
e("_setCampaignTrack","4");e("_setClientInfo","5");e("_setDetectFlash","7");e("_setDetectTitle",
"8");!1===a["16"]?(c("_setLocalGifPath",a["13"]),c("_setLocalServerMode")):a["13"]&&(c("_setLocalGifPath",a["13"]),c("_setLocalRemoteServerMode"));c("_set","hitCallback",
function(){if(m(a[""]))a[""]();b()});if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else if(a[""]){}else c("_trackPageview");window._gat||C(a[""]?B("https://","http://","stats.g.doubleclick.net/dc.js"):B("https://ssl","http://www",".google-analytics.com/ga.js"),function(){window._gat||d()},d)};_ga.b="ga";var cc=function(){this.d=[]};cc.prototype.set=function(a,b){this.d.push([a,b]);return this};cc.prototype.j=function(){for(var a={},b=0;b<this.d.length;b++)a[W(this.d[b][0])]=W(this.d[b][1]);return a};
for(var ec=function(a){this.index=a;this.j=function(){return fa(dc[a])}},_M=function(a){return new ec(a)},fc=function(a){this.j=function(){for(var b=[],d=0;d<a.length;d++)b.push(W(X[a[d]]));return b.join("")}},_T=function(a){return new fc(arguments)},gc=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}
this.j=function(){if(a[0]instanceof ec&&b(8)&&b(16))return'google_tag_manager["GTM-KJF4"].macro('+a[0].index+")";for(var d=String(W(a[0])),c=1;c<a.length;c++)d=T[a[c]](d);return d}},_E=function(a,b){return new gc(arguments)},W=function(a){var b=a;if(a instanceof ec||a instanceof cc||a instanceof fc||a instanceof gc)return a.j();if(v(a))for(var b=[],d=0;d<a.length;d++)b[d]=W(a[d]);else if(a&&"object"==typeof a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=W(a[c]))}return b},hc=function(a,b){var d=
b[a],c=d;if(d instanceof ec||d instanceof gc||d instanceof fc)c=d;else if(v(d))for(var c=[],e=0;e<d.length;e++)c[e]=hc(d[e],b);else if("object"==typeof d){var c=new cc,f;for(f in d)d.hasOwnProperty(f)&&c.set(b[f],hc(d[f],b))}return c},kc=function(a,b){for(var d=b?b.split(","):[],c=0;c<d.length;c++){var e=d[c]=d[c].split(":");0==a&&(e[1]=X[e[1]]);if(1==a)for(var f=ic(e[0]),e=d[c]={},g=0;g<f.length;g++){var k=jc[f[g]];e[k[0]]=k[1]}if(2==a)for(g=0;4>g;g++)e[g]=ic(e[g])}return d},ic=function(a){var b=
[];if(!a)return b;for(var d=0,c=0;c<a.length&&d<lc;d+=6,c++){var e=a&&a.charCodeAt(c)||65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(d);2&f&&b.push(d+1);4&f&&b.push(d+2);8&f&&b.push(d+3);16&f&&b.push(d+4);32&f&&b.push(d+5)}}return b},lc=35,X,mc=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js',_ga,'GA pageview UA-3845525-1  with Non-ssl Mirror enabled','UA-3845525-1',_v,'dl_pageVirtual','pageVirtual',_M(2),'independent.ie',true,false,'','//www.independent.ie/__utm.gif',1,'url hostname','host','url path','path',_f,'referrer','event'],nc=[],oc=0;oc<mc.length;oc++)nc[oc]=hc(oc,mc);X=nc;
var jc=kc(0,"10:0,10:1,11:2,2:3,3:4,10:5,10:6,11:7,2:8,3:9,10:10,11:11,0:12,10:13,11:14,14:15,15:16,9:17,1:18,12:19,18:20,4:18,5:18,7:18,8:18,13:21,16:18,17:22,11:23,6:24,11:25,6:26,10:27,11:28,11:29"),dc=kc(1,"G,AD,AAO,CAAAw,CAAAAD,AAAAAM,ABAAAQ"),pc=kc(1,"Z,gM"),Y=kc(1,"Awx_P"),qc=kc(2,"D:B::");var xc=function(){var a=[];return function(b){if(void 0===a[b]){var d=pc[b]&&W(pc[b]);a[b]=[d&&fa(d),d]}return a[b]}},yc=function(a,b){for(var d=b[0],c=0;c<d.length;c++)if(!a.e(d[c])[0])return!1;for(var e=b[2],c=0;c<e.length;c++)if(a.e(e[c])[0])return!1;return!0},zc=Aa=function(a,b){Ea=a;for(var d=J.get("tagTypeBlacklist"),c={name:a,C:b||ba,h:ic(),i:ic(),e:xc(),o:new ia(d)},e=0;e<qc.length;e++)if(yc(c,qc[e])){for(var f=c,g=qc[e],k=g[1],l=0;l<k.length;l++)f.h[k[l]]=!0;for(var n=g[3],l=0;l<n.length;l++)f.i[n[l]]=
!0}var q=[];for(var p=0;p<lc;p++)if(c.h[p]&&!c.i[p])if(ja(c.o,Y[p])){}else{q[p]=W(Y[p]);}c.p=q;for(var r=new ma,t=0;t<lc;t++)if(c.h[t]&&!c.i[t]&&!ja(c.o,Y[t])){var A=c.p[t],K=new la;K.m.push(Bb(A));K.k.push(Cb(A));na(r,K);fa(A,K.B,K.A)}r.addListener(c.C);0<r.f||ka(r.n);Ea=null;return 0<c.p.length};var $={set:function(a,b){J.set(a,b)},event:function(a){zc(a)},macro:function(a){return dc[a]&&fa(W(dc[a]))},r:{push:function(a){for(var b=arguments,d=0;d<b.length;d++)try{if(m(b[d][0]))b[d][0]();else $[b[d][0]].apply($,[].slice.call(b[d],1))}catch(c){}}},I:function(){var a=x["gtm"];if(a){var b=a.a;v(b)&&$.r.push.apply($.r,b);a.a=$.r;sa.push(function(){$.event("gtm.dom")});ya.push(function(){$.event("gtm.load")})}},J:function(){var a=x.google_tag_manager;a||(a=x.google_tag_manager={});a["GTM-KJF4"]||
(a["GTM-KJF4"]=$)}};$.J();$.I();(function(){var a=z("dataLayer",[]),b=x.google_tag_manager;sa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});ya.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var d=a.push;a.push=function(){var b=[].slice.call(arguments,0);d.apply(a,b);M.push.apply(M,b);return Da()};M.push.apply(M,a.slice(0));x.setTimeout(Da,0)})();
if("interactive"==y.readyState||"complete"==y.readyState)I();else{G(y,"DOMContentLoaded",I);G(y,"readystatechange",I);if(y.createEventObject&&y.documentElement.doScroll){var Ac=!0;try{Ac=!x.frameElement}catch(Bc){}Ac&&ua()}G(x,"load",I)}"complete"===y.readyState?za():G(x,"load",za);var _vs="res_ts:1371041933386000,srv_cl:48224014,ds:live,cv:8";
})()
